steps:
  # Build and push the image for 'sudden'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'dockerfile.sudden', '-t', 'europe-west1-docker.pkg.dev/bachelorthesis-421507/thesisimages/suddenexperiments:latest', '.']
    id: 'Build Sudden'

  # Build and push the image for 'gradual'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'dockerfile.gradual', '-t', 'europe-west1-docker.pkg.dev/bachelorthesis-421507/thesisimages/gradualexperiments:latest', '.']
    id: 'Build Gradual'

  # Build and push the image for 'incremental'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'dockerfile.incremental', '-t', 'europe-west1-docker.pkg.dev/bachelorthesis-421507/thesisimages/incrementalexperiments:latest', '.']
    id: 'Build Incremental'

  # Build and push the image for 'recurring'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'dockerfile.recurring', '-t', 'europe-west1-docker.pkg.dev/bachelorthesis-421507/thesisimages/recurringexperiments:latest', '.']
    id: 'Build Recurring'

images:
  - 'europe-west1-docker.pkg.dev/bachelorthesis-421507/thesisimages/gradualexperiments:latest'
  - 'europe-west1-docker.pkg.dev/bachelorthesis-421507/thesisimages/suddenexperiments:latest'
  - 'europe-west1-docker.pkg.dev/bachelorthesis-421507/thesisimages/incrementalexperiments:latest'
  - 'europe-west1-docker.pkg.dev/bachelorthesis-421507/thesisimages/recurringexperiments:latest'
